### ISSUE TITLE
React not declared as peer dependecy

### ISSUE THREAD

**Issue by tnoppeney** [andruschka/react-meteor-hooks#1]
Hi,

I'm trying to use the `useSubscription` hook in one of my functional components and get the following error:

> Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

When I use the `useState` hook in the same location, everything works fine, so 1. and 2. cannot be the reason for the error. After checking the React documentation I think that you should declare React in `peerDependencies` instead of `dependencies`, because otherwise your library uses its own instance of React.

Best regards,
Tobias

**Comment by andruschka** [comment]
oh damn thanks a lot mate. you are right!

**Comment by andruschka** [comment]
should be working now 👍
