### ISSUE TITLE
Conditional `useXXX` is not correct.

### ISSUE THREAD

**Issue by zhaoyao91** [andruschka/react-meteor-hooks#12]
Hi. I have seen such example:

```
const UserBooks = (sortBy, showLimit) => {
  const loading = useSubscription('user_books', showLimit)
  if (loading) {
    // ...
  } else {
    const allBooks = useMongoFetch(Books.find({}, { sort: { [sortBy] : -1 }}), [sortBy])
    const books = allBooks.map(/* ... */)
    // ...
  }
}
```

the `useMongoFetch` is called conditionally, which is not correct with react hooks. 

see: https://reactjs.org/docs/hooks-rules.html

**Comment by mhlmhl** [comment]
I echo this issue.  Perhaps this package was developed before the "rules of hooks" were documented...?

**Comment by andruschka** [comment]
Yep. I built that one just when the react hooks came out. I will rebuilt this package... Help welcome
Thanks for the info.
