### ISSUE TITLE
Why 'loading' is always true?

### ISSUE THREAD

**Issue by podeig** [andruschka/react-meteor-hooks#13]
Trying to implement 'react-meteor-hooks, but 'loading' variable is always true:

    import React from 'react';
    import { useSubscription, useMongoFetch } from 'react-meteor-hooks';
    import { Comments } from '../../../../collections/comments';

    export const GiveComments = (props) => {

         const loading = useSubscription('getComments');

        if (loading) {
             console.log('loading... ');
        } else {
            const allComments = useMongoFetch(Comments.find({}));
            console.log('loaded: ', allComments);
          }
        return (null);
    };

Publishing:

      Meteor.publish('getComments', function() {
        return Comments.find({});
      });

These hooks looks amazing, but can't get it to work. Why 'loading' does not stop?

**Comment by mhlmhl** [comment]
After spending a completely unreasonable amount of time trying to make "useSubscription" work with the current version of React hooks, I've concluded that it is unreliable.  I think it should be withdrawn.

See the [react-meteor-data package](https://github.com/meteor/react-packages/tree/devel/packages/react-meteor-data) and [this article](https://forums.meteor.com/t/usetracker-react-hook-lessons-learned/50000) for better alternatives.

**Comment by podeig** [comment]
It is not for production code yet. I stopped to try. Will wait to an official implementation. :)

**Comment by soodoh** [comment]
Any update on this? I am also experiencing issues with useSubscription and useMongoFetch. useSubscription always returns true and useMongoFetch is always an empty array.
```
const loading = useSubscription('clients'); // always true
const clients = useMongoFetch(Clients.find({})); // always []
```

If it's any help, we can also see this issue in useTracker.
```
const clients = useTracker(() => {
  Meteor.subscribe('clients');
  const data = Clients.find().fetch();
  console.log(data); // Actually works! Shows a full array.
  return data;
});

console.log(clients); // Always []
```

**Comment by andruschka** [comment]
I actually built this when the first version of React hooks was in beta. A lot of stuff changed now. This package will be rebuilt... Sorry for the inconvenience.
