### ISSUE TITLE
Meteor SSR error

### ISSUE THREAD

**Issue by eugle** [andruschka/react-meteor-hooks#14]
client
![image](https://user-images.githubusercontent.com/24447931/71592628-eca5b800-2b6b-11ea-8bc3-1a872097f72a.png)

error information
![image](https://user-images.githubusercontent.com/24447931/71592634-f62f2000-2b6b-11ea-8363-c9595b6b4369.png)

How can I solve this problem? Any help would be greatly appreciated

**Comment by andruschka** [comment]
`meteor add tracker` should actually do it?
