### ISSUE TITLE
How to use this package directly from NPM?

### ISSUE THREAD

**Issue by jeveldev** [andruschka/react-meteor-hooks#9]
If i import it from npm meteor throws error
here import:
`import { useSubscription, useTracker } from 'react-meteor-hooks'`
here error:
`Error: Cannot find module 'meteor/tracker'`
If put this package in /imports/... then it works, but it need to be a dependency and not part of project code

**Comment by lucaciraolo** [comment]
I ran into the same issue, make sure to add the tracker package to your meteor dependencies:
`meteor add tracker`

This should probably be mentioned in the readme for noobs such as myself :)

**Comment by jeveldev** [comment]
@lucaciraolo no it's not about there is not tracker, i have this package in dependencies list.
it is about that package compiled for NPM. Symlink to imports dir workaround.
```ln -s `pwd`/node_modules/react-meteor-hooks `pwd`/imports/ui/lib/react-meteor-hooks```

**Comment by andruschka** [comment]
Actually for me it is working from NPM. You just have to make sure you have added Tracker to Meteor.
`meteor add tracker`. But I am rebuilding this either way.
